In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     -------------------- ------------------- 30.7/60.9 kB 1.3 MB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.9 kB 991.0 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 375.8 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 359.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.2 MB ? eta -:--:--
   ---------------------------------------- 0.1/16.2 MB 544.7 kB/s eta 0:00:30
   ---------------------------------------- 0.1/16.2 MB 423.5 kB/s eta 0:00:38
    ------------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [2]:
import numpy as np

In [4]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [5]:
data

array([[[0.98291681, 0.36232695, 0.16388161, 0.18651343],
        [0.91688015, 0.06240187, 0.97762773, 0.84498597],
        [0.86369286, 0.8234679 , 0.27023661, 0.12874431]],

       [[0.96203307, 0.31253564, 0.26465147, 0.380111  ],
        [0.3083555 , 0.71566851, 0.72616463, 0.03131511],
        [0.85298591, 0.64932893, 0.05740382, 0.1062042 ]]])

In [40]:
data[0][0][0]=700

In [6]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [41]:
data

array([[[7.00000000e+02, 3.62326953e-01, 1.63881611e-01, 1.86513427e-01],
        [9.16880150e-01, 6.24018710e-02, 9.77627726e-01, 8.44985972e-01],
        [8.63692856e-01, 8.23467897e-01, 2.70236606e-01, 1.28744314e-01]],

       [[9.62033070e-01, 3.12535639e-01, 2.64651466e-01, 3.80111004e-01],
        [3.08355498e-01, 7.15668506e-01, 7.26164626e-01, 3.13151118e-02],
        [8.52985905e-01, 6.49328931e-01, 5.74038231e-02, 1.06204196e-01]]])

In [42]:
data.sort()
data

array([[[1.63881611e-01, 1.86513427e-01, 3.62326953e-01, 7.00000000e+02],
        [6.24018710e-02, 8.44985972e-01, 9.16880150e-01, 9.77627726e-01],
        [1.28744314e-01, 2.70236606e-01, 8.23467897e-01, 8.63692856e-01]],

       [[2.64651466e-01, 3.12535639e-01, 3.80111004e-01, 9.62033070e-01],
        [3.13151118e-02, 3.08355498e-01, 7.15668506e-01, 7.26164626e-01],
        [5.74038231e-02, 1.06204196e-01, 6.49328931e-01, 8.52985905e-01]]])

In [49]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [53]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes , [3,2])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 2.]


In [57]:
zeroes = np.insert(zeroes, 2 , 1)
print(zeroes)

[0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 3. 2.]


In [8]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [9]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [10]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [12]:
type(arr)

numpy.ndarray

In [ ]:
2.read

In [14]:
#attributes
shape = data.shape
size = data.size
types = data.dtype

In [15]:
shape

(2, 3, 4)

In [16]:
size

24

In [20]:
#slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data [0][0][0]

In [18]:
arr

array([[0.98291681, 0.36232695, 0.16388161, 0.18651343],
       [0.91688015, 0.06240187, 0.97762773, 0.84498597],
       [0.86369286, 0.8234679 , 0.27023661, 0.12874431]])

In [21]:
slicer

array([[0.98291681, 0.36232695, 0.16388161, 0.18651343],
       [0.91688015, 0.06240187, 0.97762773, 0.84498597]])

In [22]:
reverse

array([[0.96203307, 0.31253564, 0.26465147, 0.380111  ],
       [0.3083555 , 0.71566851, 0.72616463, 0.03131511],
       [0.85298591, 0.64932893, 0.05740382, 0.1062042 ]])

In [23]:
singleval

np.float64(0.9829168050805662)

In [24]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [25]:
list2

array([0.39725156, 0.9328747 , 0.14624512, 0.82222974, 0.4606167 ,
       0.15216416, 0.28756921, 0.47775826, 0.06050839, 0.96998601])

In [26]:
list1

array([0.21906676, 0.76830387, 0.35864185, 0.8417824 , 0.46705363,
       0.0643958 , 0.63021791, 0.26128341, 0.91405913, 0.57031891])

In [30]:
#basic math
add = np.add(list1 , list2)
sub = np.subtract(list1 , list2)
mult = np.multiply(list1 , list2)
div = np.divide(list1 , list2)
dot = np.dot(list1, list2)

In [31]:
sub


array([-0.17818479, -0.16457083,  0.21239673,  0.01955266,  0.00643692,
       -0.08776836,  0.34264869, -0.21647485,  0.85355074, -0.3996671 ])

In [32]:
dot

np.float64(2.687846620989217)

In [33]:
add

array([0.61631832, 1.70117857, 0.50488698, 1.66401214, 0.92767033,
       0.21655996, 0.91778712, 0.73904168, 0.97456752, 1.54030492])

In [34]:
#stat function
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = ([2,3])
mins = np.min(list1)
maxs = np.max(list1)


In [35]:
sqrt

np.float64(5.0)

In [36]:
ab

np.int64(2)

In [37]:
power

np.int32(128)

In [38]:
maxs

np.float64(0.9140591271010978)

In [58]:
data

array([[[1.63881611e-01, 1.86513427e-01, 3.62326953e-01, 7.00000000e+02,
         6.24018710e-02, 8.44985972e-01],
        [9.16880150e-01, 9.77627726e-01, 1.28744314e-01, 2.70236606e-01,
         8.23467897e-01, 8.63692856e-01]],

       [[2.64651466e-01, 3.12535639e-01, 3.80111004e-01, 9.62033070e-01,
         3.13151118e-02, 3.08355498e-01],
        [7.15668506e-01, 7.26164626e-01, 5.74038231e-02, 1.06204196e-01,
         6.49328931e-01, 8.52985905e-01]]])

In [59]:
np.delete(data , 0 , axis=1)

array([[[0.91688015, 0.97762773, 0.12874431, 0.27023661, 0.8234679 ,
         0.86369286]],

       [[0.71566851, 0.72616463, 0.05740382, 0.1062042 , 0.64932893,
         0.85298591]]])

In [60]:
np.save("new array",data)

In [61]:
test = np.load("new array.npy")

In [62]:
test

array([[[1.63881611e-01, 1.86513427e-01, 3.62326953e-01, 7.00000000e+02,
         6.24018710e-02, 8.44985972e-01],
        [9.16880150e-01, 9.77627726e-01, 1.28744314e-01, 2.70236606e-01,
         8.23467897e-01, 8.63692856e-01]],

       [[2.64651466e-01, 3.12535639e-01, 3.80111004e-01, 9.62033070e-01,
         3.13151118e-02, 3.08355498e-01],
        [7.15668506e-01, 7.26164626e-01, 5.74038231e-02, 1.06204196e-01,
         6.49328931e-01, 8.52985905e-01]]])